#!/usr/bin/python
# -*- coding: utf-8 -*-
countries_per_continent_dic = {
    'Africa': [
        'Morocco',
        'Algeria',
        'Angola',
        'Burkina Faso',
        'Central African Republic',
        'Chad',
        'Comoros',
        'Democratic Republic of the Congo',
        'Djibouti',
        'Ascension and Tristan da Cunha',
        'Sudan',
        'Cabo Verde',
        'Mauritius',
        'Eritrea',
        'Jersey',
        'Equatorial Guinea',
        'Guinea-Bissau',
        'Gabon',
        'Mali',
        'Sao Tome and Principe',
        'Swaziland',
        'Seychelles',
        'Madagascar',
        'Guinea',
        'Libya',
        'Mauritania',
        'Mozambique',
        'Togo',
        'Niger',
        'Tunisia',
        'Senegal',
        'The Gambia',
        'Sierra Leone',
        'Liberia',
        "Cote d'Ivoire",
        'Ghana',
        'Benin',
        'Nigeria',
        'Cameroon',
        'Republic of the Congo',
        'Namibia',
        'South Africa',
        'Botswana',
        'Zimbabwe',
        'Zambia',
        'Malawi',
        'Tanzania',
        'Burundi',
        'Rwanda',
        'Uganda',
        'Kenya',
        'Somalia',
        'Ethiopia',
        'South Sudan',
        'Egypt',
        ],
    'Europe': [
        'Spain',
        'Portugal',
        'France',
        'Italy',
        'Switzerland',
        'Albania',
        'Belgium',
        'Andorra',
        'Germany',
        'Iceland',
        'Luxembourg',
        'Lithuania',
        'Moldova',
        'Montenegro',
        'Belarus',
        'Cyprus',
        'Isle of Man',
        'Bosnia and Herzegovina',
        'Gibraltar',
        'Faroe Islands',
        'Liechtenstein',
        'Malta',
        'San Marino',
        'Greece',
        'Guernsey',
        'Netherlands',
        'Austria',
        'Croatia',
        'Monaco',
        'Slovenia',
        'Czech Republic',
        'Denmark',
        'Finland',
        'Poland',
        'Slovakia',
        'Romania',
        'Hungary',
        'Serbia',
        'Macedonia',
        'Bulgaria',
        'Ukraine',
        'Estonia',
        'Sweden',
        'Norway',
        'United Kingdom',
        'Ireland',
        ],
    'Asia': [
        'Afghanistan',
        'Armenia',
        'Azerbaijan',
        'Bahrain',
        'Bangladesh',
        'Bhutan',
        'Brunei',
        'Burma',
        'Cambodia',
        'China',
        'Georgia',
        'Hong Kong',
        'India',
        'Indonesia',
        'Iran',
        'Iraq',
        'Israel',
        'Palestine',
        'Japan',
        'Jordan',
        'Kazakhstan',
        'Kiribati',
        'North Korea',
        'South Korea',
        'Kosovo',
        'Kuwait',
        'Kyrgyzstan',
        'Laos',
        'Latvia',
        'Lebanon',
        'Lesotho',
        'Macau',
        'Malaysia',
        'Maldives',
        'Mongolia',
        'Nepal',
        'Oman',
        'Pakistan',
        'Philippines',
        'Qatar',
        'Russia',
        'Saudi Arabia',
        'Singapore',
        'Sri Lanka',
        'Syria',
        'Taiwan',
        'Tajikistan',
        'Thailand',
        'Timor-Leste',
        'Turkey',
        'Turkmenistan',
        'United Arab Emirates',
        'Uzbekistan',
        'Vietnam',
        'West Bank',
        'Yemen',
        ],
    'North America': [
        'USA',
        'Canada',
        'Mexico',
        'Cuba',
        'Jamaica',
        'Curacao',
        'Dominican Republic',
        'Bermuda',
        'Puerto Rico',
        'Honduras',
        'Anguilla',
        'Aruba',
        'Panama',
        'Guatemala',
        'Haiti',
        'Saint Kitts and Nevis',
        'Saint Lucia',
        'Dominica',
        'Saint Martin',
        'British Virgin Islands',
        'Saint Pierre and Miquelon',
        'Greenland',
        'Saint Vincent and the Grenadines',
        'Virgin Islands',
        'Sint Maarten',
        'Barbados',
        'Belize',
        'Antigua and Barbuda',
        'Costa Rica',
        'The Bahamas',
        'Cayman Islands',
        'Nicaragua',
        'Grenada',
        'El Salvador',
        ],
    'South America': [
        'Colombia',
        'Trinidad and Tobago',
        'Ecuador',
        'Peru',
        'Brazil',
        'Bolivia',
        'Chile',
        'Argentina',
        'Uruguay',
        'Venezuela',
        'Paraguay',
        'Suriname',
        'Guyana',
        'Falkland Island',
        'Falkland Islands (Islas Malvinas)',
        ],
    'Oceania': [
        'Australia',
        'New Zealand',
        'Papua New Guinea',
        'American Samoa',
        'New Caledonia',
        'Northern Mariana Islands',
        'Niue',
        'Palau',
        'Samoa',
        'Solomon Islands',
        'Tonga',
        'Tuvalu',
        'Vanuatu',
        'Guam',
        'French Polynesia',
        'Fiji',
        'Cook Islands',
        'Marshall Islands',
        'Federated States of Micronesia',
        ],
    }

	
